services:
  postgres:
    image: postgres:15
    container_name: vratnice_db
    restart: always
    environment:
      POSTGRES_DB: vratnicedb
      POSTGRES_USER: vratnice
      POSTGRES_PASSWORD: DipPra123*
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data


volumes:
  postgres_data:
