services:
  vratnice_postgres:
    image: postgres:15
    container_name: vratnice_postgres
    environment:
      POSTGRES_DB: vratnicedb
      POSTGRES_USER: vratnice
      POSTGRES_PASSWORD: DipPra123*
    ports:
      - "5432:5432"
    volumes:
      - ./vratnice_data:/var/lib/postgresql/data
